version: '3.1'
services:
  stats-server:
    build: ./stats-service/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
          - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
      - SPRING_DATASOURCE_USER=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stat-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats-db


  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main-db
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - CLIENT_URL=http://stat-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_DB=ewm-main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root