version: '3.1'
services:
  stats-server:
    build: ./stats-service/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
          - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
      - SPRING_DATASOURCE_USER=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stat-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats-db

#  main-service:
#    ports:
#      - "8080:8080"
#    environment:
#      - CLIENT_URL=http://stat-server:9090
#
#
#  ewm-db:
#    image: postgres:14-alpine
